name: chat_application_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^6.1.2
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  dio_http_formatter: ^3.3.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  form_validator: ^2.1.1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  go_router: ^17.0.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  logger: ^2.6.0
  multiple_result: ^5.2.0
  riverpod_annotation: null
  shared_preferences: ^2.3.1
  speech_to_text: ^7.3.0
  sqflite: ^2.4.2

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  json_serializable: ^6.11.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
