name: chat_application_task
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^10.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  multiple_result: ^5.2.0
  shared_preferences: ^2.3.1
  freezed_annotation: ^3.1.0
  dio: ^5.9.1
  dio_http_formatter: ^3.3.1
  cached_network_image: ^3.2.0
  logger: ^2.6.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  sqflite: ^2.4.2
  internet_connection_checker: ^3.0.1
  go_router: ^17.0.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

  freezed: ^3.2.3
  json_serializable: ^6.11.0
  riverpod_generator: ^4.0.0+1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

